# Generated by Django 5.2.6 on 2025-09-25 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_payment_received'),
        ('users', '0003_verificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('is_complaint', models.BooleanField(default=False)),
                ('complaint_category', models.CharField(blank=True, max_length=200)),
                ('complaint_description', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.medicprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['medic', 'rating'], name='reviews_rev_medic_i_7a7b3c_idx'), models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx')],
            },
        ),
    ]
