# Generated by Django 5.2.6 on 2025-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_title_order_address_order_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
